<a href="https://colab.research.google.com/github/jacoaji02/speech-ai-model-learning/blob/main/day_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b = np.array([4,5,6])
print(b)

[4 5 6]


In [ ]:
print(a+b)

[5 7 9]


In [ ]:
print(a-b)

[-3 -3 -3]


In [ ]:
print(a.dot(b))

32


In [ ]:
print(a.shape)

(3,)


In [1]:
import numpy as np

scores = np.array([45, 88, 92, 60, 75, 55])

# TO-DO: Calculate the min and max of the scores array
# Then apply the formula to scale the data between 0 and 1
# Your code here:
minimum_score = scores.min()
maximum_score = scores.max()
scaled_scores = (scores - minimum_score) / (maximum_score - minimum_score)

print(scaled_scores)

[0.         0.91489362 1.         0.31914894 0.63829787 0.21276596]


In [4]:
movie_genres = ['Action', 'Comedy', 'Sci-Fi']
Customer_Preferences = [5, 1, 4]
Movie_Profile = [4, 0, 5]

# TO-DO: Create the two 1D arrays and find their dot product using np.dot()
# Does this customer have a high similarity score with this movie?
# Your code here:
customer_preference = np.array([5,1,4])
movie_profile = np.array([4,0,5])
similarity_score = np.dot(customer_preference, movie_profile)
print(similarity_score)


40


In [7]:
# Generate a random vector
v = np.array([3.0, 4.0, 12.0])

# TO-DO:
# 1. Calculate the magnitude of v
# 2. Divide v by its magnitude to create v_hat
# 3. Check your work: verify that np.linalg.norm(v_hat) equals 1.0
# Your code here:

v_mag = np.linalg.norm(v)
print(v_mag)
v_hat = v / v_mag
print(v_hat)
v_hat_mag = np.linalg.norm(v_hat)
print(v_hat_mag)

13.0
[0.23076923 0.30769231 0.92307692]
1.0


In [11]:
# Rows: Movie 0, Movie 1, Movie 2, Movie 3
# Columns: Action, Comedy, Romance
movie_matrix = np.array([
    [5, 1, 0],  # Movie 0 (Pure Action)
    [1, 5, 4],  # Movie 1 (Rom-Com)
    [0, 0, 5],  # Movie 2 (Pure Romance)
    [4, 4, 1]   # Movie 3 (Action-Comedy)
])

user_profile = np.array([4, 5, 1])

# TO-DO: Use a single matrix-vector dot product operation to find the scores for all 4 movies at once.
# Hint: Look up how np.dot() works when multiplying a Matrix by a Vector.
# Which movie has the highest recommendation score for this user?
# Your code here:
mat_vac_dot = np.dot(movie_matrix, user_profile)
print(mat_vac_dot)
reco_movie = np.argmax(mat_vac_dot)
print(reco_movie)

[25 33  5 37]
3
