<a href="https://colab.research.google.com/github/jacoaji02/speech-ai-model-learning/blob/main/Day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""import numpy as np

# 1. Create a 1D array of numbers from 10 to 19
arr_1d = np.arange(10, 20)
print("1D Array:", arr_1d)

# 2. Reshape it into a 2D matrix (5 rows, 2 columns)
matrix = arr_1d.reshape(5, 2)
print("\nReshaped 2D Matrix:\n", matrix)

# 3. Extract the third row of the matrix
third_row = matrix[2, :]
print("\nThird Row:", third_row)

# 4. Perform a vector operation: Multiply every element in the matrix by 2
doubled_matrix = matrix * 2
print("\nDoubled Matrix:\n", doubled_matrix)"""

In [2]:
"""import numpy as np

# 1. Create a 1D array of numbers from 10 to 19
arr_1d = np.arange(10, 20)
print("1D Array:", arr_1d)"""

import numpy as np

arr_id = np.arange(10, 20)
# print("1D Array:", arr_id)


1D Array: [10 11 12 13 14 15 16 17 18 19]


In [4]:
"""# 2. Reshape it into a 2D matrix (5 rows, 2 columns)"""

matrix = arr_id.reshape(5, 2)
print(matrix)

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [7]:
"""# 3. Extract the third row of the matrix"""

new = matrix[2]
print(new)

[14 15]


In [8]:
# 4. Perform a vector operation: Multiply every element in the matrix by 2

multi = matrix * 2
print(multi)

[[20 22]
 [24 26]
 [28 30]
 [32 34]
 [36 38]]


In [10]:
"""import numpy as np

# 1. Generate the random 4x4 matrix
matrix = np.random.randint(1, 51, size=(4, 4))
print("Original Matrix:\n", matrix)

# 2. Apply the mask to replace values > 25 with -1
# Write your code here:"""

matrix_2 = np.random.randint(1, 51, size=(4, 4))
print(matrix_2)

matrix_2[matrix_2 > 25] = -1
print(matrix_2)


[[10 48 18  1]
 [45 12 30  8]
 [ 1 47 39  6]
 [ 5  3  3 25]]
[[10 -1 18  1]
 [-1 12 -1  8]
 [ 1 -1 -1  6]
 [ 5  3  3 25]]
