<a href="https://colab.research.google.com/github/jacoaji02/speech-ai-model-learning/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

x = torch.tensor([1,2,3])
print(x)

tensor([1, 2, 3])


In [ ]:
x.shape
print(x.ndim)

1


In [ ]:
"""Beginner Challenge 1: The Dimension AuditScenario: You are handed an unknown tensor tracking monthly retail store data.
Your job is to inspect its structural properties before passing it to a neural network.
Task: Create a $3 \times 4$ floating-point tensor containing any numbers.
Print its shape, total number of dimensions, and its underlying datatype."""

'Beginner Challenge 1: The Dimension AuditScenario: You are handed an unknown tensor tracking monthly retail store data.\nYour job is to inspect its structural properties before passing it to a neural network.\nTask: Create a $3 \times 4$ floating-point tensor containing any numbers.\nPrint its shape, total number of dimensions, and its underlying datatype.'

In [ ]:
data = torch.rand(3,4)

shape_ = data.shape
d_type = data.dtype
dim = data.ndim
print(data)
print('shape: ', shape_)
print('data type: ', d_type)
print('dimension: ', dim)

tensor([[0.6355, 0.7098, 0.1669, 0.0555],
        [0.1562, 0.8767, 0.4503, 0.6998],
        [0.8977, 0.7472, 0.2454, 0.3813]])
shape:  torch.Size([3, 4])
data type:  torch.float32
dimension:  2


In [ ]:
"""Beginner Challenge 2: Device-Agnostic Setup
Scenario: You want your deep learning script to run smoothly on any machine—whether it's a teammate's laptop (CPU) or a high-powered cloud server (GPU).

Task: Write the device-agnostic setup line to dynamically detect CUDA. Create a random tensor of shape (5, 5) and move it directly to that target device."""

"Beginner Challenge 2: Device-Agnostic Setup\nScenario: You want your deep learning script to run smoothly on any machine—whether it's a teammate's laptop (CPU) or a high-powered cloud server (GPU).\n\nTask: Write the device-agnostic setup line to dynamically detect CUDA. Create a random tensor of shape (5, 5) and move it directly to that target device."

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

random_matrix = torch.rand(5,5)
gpu_ready_matrix = random_matrix.to(device)
print("Matrix Location:        ", gpu_ready_matrix.device)
print("-" * 40)

cpu
Matrix Location:         cpu
----------------------------------------


In [ ]:
"""ntermediate Challenge 3: Tensor Math & TrackingScenario: You have a vector of raw prediction scores ($Z$).
You need to find the highest score, its index location, and verify where the calculation took place.
Task: 1. Create a 1D tensor with the values [-2.5, 4.8, 0.3, 9.1, -1.2].
2. Find and print the maximum value in the tensor using torch.max().
3. Find and print the index position of that maximum value using torch.argmax()."""

'ntermediate Challenge 3: Tensor Math & TrackingScenario: You have a vector of raw prediction scores ($Z$).\nYou need to find the highest score, its index location, and verify where the calculation took place.\nTask: 1. Create a 1D tensor with the values [-2.5, 4.8, 0.3, 9.1, -1.2].\n2. Find and print the maximum value in the tensor using torch.max().\n3. Find and print the index position of that maximum value using torch.argmax().'

In [ ]:
data_2 = torch.tensor([-2.5, 4.8, 0.3, 9.1, -1.2])
print(data_2)
maximum_value = torch.max(data_2)
print(maximum_value.item())
index_max = torch.argmax(data_2)
print(index_max.item())

tensor([-2.5000,  4.8000,  0.3000,  9.1000, -1.2000])
9.100000381469727
3


In [ ]:
"""  Challenge 1: The Image Batch Reshaper (Computer Vision Pipeline)
Scenario: In Computer Vision, deep learning models accept images in batches shaped as [Batch_Size, Channels, Height, Width].
However, before passing this data into a standard dense hidden layer, you must flatten the images into a single long vector of pixels per image while keeping the batch dimension intact.
Setup: Create a random 4D tensor representing a batch of images with shape (32, 3, 28, 28)—meaning 32 images, 3 color channels (RGB), and $28 \times 28$ pixels.
Your Task:
1. Print the original tensor's shape.
2. Use .reshape() or .view() to flatten the images so that the new tensor has a shape of exactly (32, 2352). (Hint: $3 \times 28 \times 28 = 2352$).
3. Verify that the total number of elements inside the tensor did not change. """

"  Challenge 1: The Image Batch Reshaper (Computer Vision Pipeline)\nScenario: In Computer Vision, deep learning models accept images in batches shaped as [Batch_Size, Channels, Height, Width].\nHowever, before passing this data into a standard dense hidden layer, you must flatten the images into a single long vector of pixels per image while keeping the batch dimension intact.\nSetup: Create a random 4D tensor representing a batch of images with shape (32, 3, 28, 28)—meaning 32 images, 3 color channels (RGB), and $28 \times 28$ pixels.\nYour Task:\n1. Print the original tensor's shape.\n2. Use .reshape() or .view() to flatten the images so that the new tensor has a shape of exactly (32, 2352). (Hint: $3 \times 28 \times 28 = 2352$).\n3. Verify that the total number of elements inside the tensor did not change. "

In [ ]:
data = torch.rand(32,3,28,28)
image_tensor = torch.tensor(data)
tensor_shape = image_tensor.shape
print(tensor_shape)
new_shape = image_tensor.reshape(32, 2352)
print(new_shape.shape)
print(image_tensor.size())
print(new_shape.size())

torch.Size([32, 3, 28, 28])
torch.Size([32, 2352])
torch.Size([32, 3, 28, 28])
torch.Size([32, 2352])


/tmp/ipykernel_2964/3877439070.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  image_tensor = torch.tensor(data)


In [ ]:
data = torch.tensor([1,7,6,5,7,8,6,9,11,7,2,1])
print(data.shape)
print(data.reshape(3,4))

torch.Size([12])
tensor([[ 1,  7,  6,  5],
        [ 7,  8,  6,  9],
        [11,  7,  2,  1]])


In [ ]:
"""Beginner: Create a 2D tensor of shape $(3, 3)$ filled with random numbers.
Print its shape, data type, and the device it is currently on (CPU or GPU)."""

'Beginner: Create a 2D tensor of shape $(3, 3)$ filled with random numbers. \nPrint its shape, data type, and the device it is currently on (CPU or GPU).'

In [ ]:
data = torch.rand(3,3)
tensor_data = torch.tensor(data)
print(tensor_data.shape)
print(tensor_data.dtype)
print(tensor_data.device)

torch.Size([3, 3])
torch.float32
cpu


/tmp/ipykernel_2964/3562415819.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tensor_data = torch.tensor(data)


In [ ]:
"""Intermediate: Create a 1D tensor with values from 0 to 11.
Reshape it into a $(3, 4)$ tensor. Extract the entire 2nd row, and then extract the last column."""

'Intermediate: Create a 1D tensor with values from 0 to 11. \nReshape it into a $(3, 4)$ tensor. Extract the entire 2nd row, and then extract the last column.'

In [ ]:
data = torch.tensor([0,1,2,3,4,5,6,7,8,9,10,11])
reshape_data = data.reshape(3,4)
second_raw = reshape_data[1,:]
first_column = reshape_data[:,0]
print('raw_data: ', data)
print('reshape data: ', reshape_data)
print('second raw: ',second_raw)
print('first column: ',first_column)

raw_data:  tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
reshape data:  tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
second raw:  tensor([4, 5, 6, 7])
first column:  tensor([0, 4, 8])


In [ ]:
"""Imagine you want to predict a house's price based on 3 simple features:

1) Square footage (Size)

2) Number of bedrooms

3) Zip code crime rate

Because a house price is a continuous number (e.g., $350,000), this is a Regression problem.

The Plan for Our Network
We will use the nn module to build a network that looks like this:

Input Layer: Takes our 3 features.

Hidden Layer: A layer of 8 neurons to find hidden patterns between size, rooms, and location.

Activation (ReLU): To make sure the network can understand non-linear relationships (e.g., maybe a house that is too big actually drops in value if it has zero bedrooms).

Output Layer: A single neuron that spits out the predicted price."""

"Imagine you want to predict a house's price based on 3 simple features:\n\n1) Square footage (Size)\n\n2) Number of bedrooms\n\n3) Zip code crime rate\n\nBecause a house price is a continuous number (e.g., $350,000), this is a Regression problem.\n\nThe Plan for Our Network\nWe will use the nn module to build a network that looks like this:\n\nInput Layer: Takes our 3 features.\n\nHidden Layer: A layer of 8 neurons to find hidden patterns between size, rooms, and location.\n\nActivation (ReLU): To make sure the network can understand non-linear relationships (e.g., maybe a house that is too big actually drops in value if it has zero bedrooms).\n\nOutput Layer: A single neuron that spits out the predicted price."

Task 1: Prepare the Data
Before building a model, you need data. In PyTorch, all data must be converted into Floating Point Tensors (torch.float32), and inputs/targets must be separated.
Your Objective: Create your input features (X) and your true target prices (y).
The Math: If $X$ has a shape of $(2, 3)$ (2 houses, 3 features each), then $y$ must have a shape of $(2, 1)$ (2 houses, 1 price each).

In [ ]:
X = torch.tensor([[1.6, 4.0, 0.2],
                 [2.8, 3.0, 0.8]], dtype = torch.float32)
Y = torch.tensor([[10], [7]], dtype = torch.float32)

"""Task 2: Instantiate the Model Architecture
This is where we bring our nn.Module blueprint to life.

Your Objective: Create an instance of the HousePricePredictor class.

Why it matters: When you instantiate the model, PyTorch automatically generates random numbers for the weights and biases inside your nn.Linear layers. This is why the initial predictions are completely wrong!"""


In [ ]:
import torch.nn as nn
import torch.optim as optim

class HousePredictor(nn.Module):
  def __init__(self):
    super().__init__()
    self.hidden_layer = nn.Linear(3, 8)
    self.activation = nn.ReLU()
    self.output_layer = nn.Linear(8, 1)

  def forward(self, x):
    return self.output_layer(self.activation(self.hidden_layer(x)))

model = HousePredictor()

loss_function = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

for epoch in range(100):
  predictions = model(X)
  loss = loss_function(predictions, Y)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()
  if (epoch + 1) % 2 == 0:
    print(f'epoch[{epoch+1} / 100] | current error: {loss.item():.4f}')

print("\n--- Final Results ---")
# Turn off the tracking engine
with torch.no_grad():
    final_predictions = model(X)

# Let's see how close it got!
print("Target Prices:\n", Y)
print("Model's Trained Predictions:\n", final_predictions)

epoch[2 / 100] | current error: 50.7154
epoch[4 / 100] | current error: 44.6193
epoch[6 / 100] | current error: 38.8700
epoch[8 / 100] | current error: 33.4735
epoch[10 / 100] | current error: 28.4881
epoch[12 / 100] | current error: 23.8803
epoch[14 / 100] | current error: 19.6581
epoch[16 / 100] | current error: 15.8536
epoch[18 / 100] | current error: 12.5016
epoch[20 / 100] | current error: 9.6466
epoch[22 / 100] | current error: 7.3023
epoch[24 / 100] | current error: 5.4821
epoch[26 / 100] | current error: 4.1870
epoch[28 / 100] | current error: 3.3859
epoch[30 / 100] | current error: 3.0098
epoch[32 / 100] | current error: 2.9541
epoch[34 / 100] | current error: 3.0915
epoch[36 / 100] | current error: 3.2943
epoch[38 / 100] | current error: 3.4590
epoch[40 / 100] | current error: 3.5233
epoch[42 / 100] | current error: 3.4705
epoch[44 / 100] | current error: 3.3201
epoch[46 / 100] | current error: 3.1116
epoch[48 / 100] | current error: 2.8880
epoch[50 / 100] | current error: 2.

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

torch.manual_seed(42)

# 1. SCALED DATA (Divided square footage by 1000 to keep numbers small and balanced)
X = torch.tensor([
    [2.4, 3.0, 0.02],
    [1.2, 1.0, 0.08],
    [3.0, 4.0, 0.01]
], dtype=torch.float32)

Y = torch.tensor([[450.0], [210.0], [580.0]], dtype=torch.float32)

class HousePredictor(nn.Module):
  def __init__(self):
    super().__init__()
    # 2. INCREASED CAPACITY (Changed from 8 to 16 hidden neurons)
    self.hidden_layer = nn.Linear(3, 16)
    self.activation = nn.ReLU()
    self.output_layer = nn.Linear(16, 1)

  def forward(self, x):
    return self.output_layer(self.activation(self.hidden_layer(x)))

model = HousePredictor()
loss_function = nn.MSELoss()

# 3. TUNED LEARNING RATE
optimizer = optim.Adam(model.parameters(), lr=0.03)

# 4. MORE EPOCHS (Increased from 100 to 500)
for epoch in range(500):
  predictions = model(X)
  loss = loss_function(predictions, Y)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  if (epoch + 1) % 100 == 0:
    print(f'Epoch [{epoch+1}/500] | Current Error: {loss.item():.4f}')

print("\n--- Final Results ---")
with torch.no_grad():
    final_predictions = model(X)
    print("Targets:\n", Y)
    print("Predictions:\n", final_predictions)

Epoch [100/500] | Current Error: 398.5930
Epoch [200/500] | Current Error: 141.0123
Epoch [300/500] | Current Error: 98.4939
Epoch [400/500] | Current Error: 64.9442
Epoch [500/500] | Current Error: 41.5609

--- Final Results ---
Targets:
 tensor([[450.],
        [210.],
        [580.]])
Predictions:
 tensor([[454.6305],
        [217.6062],
        [573.3046]])


In [17]:
import torch
import torch.nn as nn
import torch.optim as optim

review_1 = "Great movie, love it"
review_2 = "Bad acting, terrible plot"
review_3 = "Great overall experience."
review_4 = "It was a bad choice."

vocab = ["Great", "Love", "Bad", "Terrible"]

torch.manual_seed(42)

X = torch.tensor([
    [1.0, 1.0, 0.0, 0.0],
    [0.0, 0.0, 1.0, 1.0],
    [1.0, 0.0, 0.0, 0.0],
    [0.0, 0.0, 1.0, 0.0]], dtype=torch.float32)

Y = torch.tensor([[1.0], [0.0], [1.0], [0.0]], dtype = torch.float32)

class SentimentAnalysis(nn.Module):
  def __init__(self):
    super().__init__()
    self.hidden_layer = nn.Linear(4, 8)
    self.activation = nn.ReLU()
    self.output_layer = nn.Linear(8, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, X):
    return self.sigmoid(self.output_layer(self.activation(self.hidden_layer(X))))

model = SentimentAnalysis()

loss_function = nn.BCELoss()

optimizer = optim.Adam(model.parameters(), lr=0.05)

for epoch in range(100):
  predictions = model(X)
  loss = loss_function(predictions, Y)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()
  if (epoch + 1) % 20 == 0:
    print(f'epoch[{epoch+1}/100] | current error: {loss.item(): .4f}')

with torch.no_grad():
  final_output = model(X)
  binary_prediction = (final_output > 0.5).float()
  correct = (binary_prediction == Y).sum()
  accuracy = (correct / len(Y)) * 100
  print(f"Accuracy of the model: {accuracy: .4f}")



epoch[20/100] | current error:  0.0048
epoch[40/100] | current error:  0.0002
epoch[60/100] | current error:  0.0001
epoch[80/100] | current error:  0.0001
epoch[100/100] | current error:  0.0001
Accuracy of the model:  100.0000
