<a href="https://colab.research.google.com/github/jacoaji02/speech-ai-model-learning/blob/main/vectorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
import torch

sentences = [
    "I love machine learning",
    "NLP is amazing and fun",
    "I love programming Python",
    "Deep learning is deep",
    "Python is fun for NLP"
]

# --- Exercise 1: Tokenize ---
# TODO: Split the sentences above into lists of lowercased words.
tokenized_sentences = [ s.lower().split() for s in sentences ]
vocabulary = []

for sentence in tokenized_sentences:
    for word in sentence:
        vocabulary.append(word)


unique_words = sorted(list(set(vocabulary)))

# --- Exercise 2: Build a Vocabulary Map ---
# TODO: Extract every unique word from your tokens and map them to a unique ID number.
# Hint: Start with "[PAD]": 0 to leave room for padding sequences later.
vocab = {"[PAD]": 0}

for index, word in enumerate(unique_words):
    vocab[word] = index + 1



# --- Exercise 3: Convert Text to Token IDs ---
# TODO: Substitute the words in your sentences with their matching numeric index from your vocab map.
token_ids_dataset = []

for sentence in tokenized_sentences:
    token_ids = []
    for word in sentence:
        token_ids.append(vocab[word])
    token_ids_dataset.append(token_ids)

print(token_ids_dataset)


# --- Exercise 4 & 5: Random Embeddings & Vector Similarity ---
# TODO: Create a random NumPy array matrix of shape (vocab_size, embedding_dimension=4).
# Then, slice out the vector for two words and calculate their Cosine Similarity.
np.random.seed(42)

embedding_dimension = 4
vocab_size = len(vocab)

embedding_matrix = np.random.rand(vocab_size, embedding_dimension)
print(embedding_matrix)

def cosine_similarity(v1, v2):
    # TODO: Implement the cosine similarity math equation: (A • B) / (||A|| * ||B||)
    dot_product = np.dot(v1,v2)

    normalized_v1 = np.linalg.norm(v1)
    normalized_v2 = np.linalg.norm(v2)

    similarity = dot_product / (normalized_v1 * normalized_v2)

    return similarity

print(cosine_similarity(embedding_matrix[1], embedding_matrix[2]))


[[6, 9, 10, 8], [11, 7, 1, 2, 5], [6, 9, 12, 13], [3, 8, 7, 3], [13, 7, 5, 4, 11]]
[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]
 [0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378 0.51423444]
 [0.59241457 0.04645041 0.60754485 0.17052412]
 [0.06505159 0.94888554 0.96563203 0.80839735]
 [0.30461377 0.09767211 0.68423303 0.44015249]
 [0.12203823 0.49517691 0.03438852 0.9093204 ]
 [0.25877998 0.66252228 0.31171108 0.52006802]
 [0.54671028 0.18485446 0.96958463 0.77513282]
 [0.93949894 0.89482735 0.59789998 0.92187424]]
[0.15601864 0.15599452 0.05808361 0.86617615]
[0.60111501 0.70807258 0.02058449 0.96990985]
0.8691049731271953
